[versions]
minecraft = "1.21"
fabric-loader = "0.15.11"
fabric-api = "0.100.4+1.21"
fabric_language_kotlin = "1.11.0+kotlin.2.0.0"
joml = "1.10.5"
sodium = "mc1.21-0.5.11"
mod_menu = "11.0.1"
#emi = "1.1.0+1.20.4"

[libraries]
minecraft = { module = "com.mojang:minecraft", version.ref = "minecraft" }

fabric_loader = { module = "net.fabricmc:fabric-loader", version.ref = "fabric-loader" }
fabric-api = { module = "net.fabricmc.fabric-api:fabric-api", version.ref = "fabric-api" }
fabric_language_kotlin = { module = "net.fabricmc:fabric-language-kotlin", version.ref = "fabric_language_kotlin" }

joml = { module = "org.joml:joml", version.ref = "joml" }
sodium = { module = "maven.modrinth:sodium", version.ref = "sodium" }

mod_menu = { module = "com.terraformersmc:modmenu", version.ref = "mod_menu" }
#emi = { module = "dev.emi:emi-fabric", version.ref = "emi" }

[bundles]
dev_mods = [ "joml", "sodium" ]
dependencies = [ "mod_menu" ]

[plugins]
fabric_loom = { id = "fabric-loom", version = "1.6-SNAPSHOT" }
grgit = { id = "org.ajoberstar.grgit", version = "5.0.0-rc.3" }
dokka = { id = "org.jetbrains.dokka", version = "1.9.10" }