name: Suggestions
description: Create a suggestion for Softer Pastels
labels: [ "suggestion" ]
body:
  - type: textarea
    attributes:
      label: What is your suggestion?
      description: Describe clearly what the suggestion is
    validations:
      required: true

  - type: textarea
    attributes:
      label: How would this improve on the gameplay?
      description: What about said suggestion would improve the mod and help it?
    validations:
      required: true

  - type: textarea
    attributes:
      label: Contextual Pictures and/or Videos
      description: Do you have any frame of reference for said feature?
    validations:
      required: false

  - type: textarea
    attributes:
      label: Additional Context
      description: Is there anything else that should be known with this suggestion?
    validations:
      required: false